// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ugbbnhqxqkpctdqlmnzf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVnYmJuaHF4cWtwY3RkcWxtbnpmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyNjAzMTMsImV4cCI6MjA3MDgzNjMxM30.znER9o6dx-szHXF2tRAds8xz-yOidfPwiz5S6Zgj8bE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});